### ISSUE TITLE
tmn apply

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#11]
As your suggestion, we should have a command to apply the node to become a candidate.

The command: `tmn apply`

For ideally, we should web3.py.
For save time for first test, we can use the api at: https://github.com/tomochain/tomomaster/issues/128

**Comment by thanhson1085** [comment]
yep, for user, it is lower priority than #23.

For auto-deployment, this will be useful

**Comment by etienne-napoleone** [comment]
I think for auto deployment we can just `curl`
Closing this for now as other solutions than `tmn` are being explored and this is really low priority
