### ISSUE TITLE
Some improvements for tmn start

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#23]
the params for `tmn start` should be optional:
- `--pkey`  if empty, let create a account 
- `--name`  if empty, let create a random name
- `--net` if empty, default `testnet` or `mainnet` (when available)

**Comment by etienne-napoleone** [comment]
- `--pkey`: So when implemented we should had the account private key in inspect?
- `--name`: If think it's better to force people to use name than having nodes names "n1i2u5b_12jn56"
- `--net`: yup, we can put testnet by default

**Comment by thanhson1085** [comment]
--pkey: can show pkey by using `tmn inspect --pkey`, attually, private key of coinbase is not important to use. so we can implement it later
--name: i think do need to force people in this case
It is some small improvement, just do when we have more time.

**Comment by etienne-napoleone** [comment]
@thanhson1085 I started working on this in https://github.com/tomochain/tmn/tree/feature/improvestart
There is no easy way to get the private key tho...
We could save it in a file, but I'm not sure it is very nice security wise

**Comment by etienne-napoleone** [comment]
so:
- pkey: would have to store it, which is a bad idea.
- name: we agreed that we do need people to chose a name
- net: we can put testnet by default, but I'm not sure to see the point. If we think about it, why should it be optional? To make the UX easier? But actually the default might not be what they want and this would result in more action from their part.

So I'm closing this issue for now, feel free to reopen it if someone have better ideas
