### ISSUE TITLE
Add a way to import a node configuration/data

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tmn#26]
`tmn` needs a way of importing a node configuration in case of migrations

**Comment by ngtuna** [comment]
and importing chain data too. `tomo` cli supports export and import commands already.

```
$ tomo --help
NAME:
   tomo - the tomochain command line interface

   Copyright (c) 2018 Tomochain

USAGE:
   tomo [options] command [command options] [arguments...]

VERSION:
   1.0.0-stable-d639ce2a

COMMANDS:
   ...
   export      Export blockchain into file
   import      Import a blockchain file
   ...
```

**Comment by etienne-napoleone** [comment]
This will probably not be implemented as [tomochain/create-tomochain-masternode](https://github.com/tomochain/create-tomochain-masternode) will be the prefered tool over tmn when it comes out.
