### ISSUE TITLE
Encrypt private key by passpharse

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#29]
The private key is stored in masternode, it should be encrypted by passpharse.
It will improve the security

**Comment by etienne-napoleone** [comment]
This issue is actually related to the [tomochain/tomochain](https://github.com/tomochain/tomochain) repo. I created https://github.com/tomochain/tomochain/issues/193

**Comment by thanhson1085** [comment]
Yes, not only remove private_key file, but `tmn` also should provide `--password` option. So use can input they password to encrypt the private key
https://github.com/tomochain/tomochain/blob/e20d9797fff6af3d655bd648f53c2c2bd7a74959/docker/tomochain/entrypoint.sh#L100

**Comment by thanhson1085** [comment]
I think that is enough, should close this issue.
