### ISSUE TITLE
Unique identity = Coinbase address

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#38]
To simplify the flow, we should use coinbase address as unique identify.

Telegraf/grafana will use coinbase address as node identify.
For stats page, we will use node name.

So, `tmn inspect` just show coinbase address.

Pros:
- one is more simple that two
- node name will be presented on the stats page instead of `unique identify`, more user friendly
- Only need to update tomomaster when user change pkey, this is a big improvement

**Comment by thanhson1085** [comment]
40 chars is OK, it only work in background, and present in grafana.

**Comment by etienne-napoleone** [comment]
In case we implement that, it will be a non retro-compatible release

**Comment by thanhson1085** [comment]
Yep, So we need to define the steps to upgrade the version. So user can follow the steps to upgrade.
It seems we have more works need to do for this task, and masternodes need to reset the data, right?

**Comment by etienne-napoleone** [comment]
I think so. tmn is flexible regarding changes inside the containers, but isn't when it concern changes to persistent config who is generated at first start.
Another option would be to add a flag to `tmn remove` to skip the volume deleting.
could be like this:
```
tmn remove --skip-volume
tmn start --name ... (same as before or the old volume will be ignored and it will start from scratch) --etc...
```
Or maybe we could wait for those kind of stuff:
- new networking (tested in devnet)
- slashing
- breaking changes in tmn

and reset testnet to get on a sane base?

**Comment by thanhson1085** [comment]
We have a plan to release TomoChain version 1.0.0 in next 3 weeks (includes Penalty, Double Validation).
We will deploy the new version to the testnet, it will require the hark-folk, We hope that masternode owners do not need to reset the chain. (now syncing data will take a lot of time)

Adding more params for `tmn remove` and `tmn start` to make it more flexible, that is a good solution we have. But that will require us to write more code.
