### ISSUE TITLE
Collecting logs

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#39]
In order to improve quality of product `tomochain`, we should enable collecting logs, and push to the centralized logs system.
We also need to provide an option so that use is able to disable collecting logs if they want.

**Comment by etienne-napoleone** [comment]
Might be easier to just add something like `tmn report` who create a zip file with the last 10'000 log lines of both containers that they can just upload to us.

**Comment by etienne-napoleone** [comment]
Probably not needed. People use docker logs directly
