### ISSUE TITLE
Auto-update TomoChain

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#46]
It is not an easy feature, but quite important for TomoChain.

Tmn should provide an option auto-update (default true). So when we release a TomoChain stable version, Tmn will automatically download and update to the node.

This is a good feature to avoid hardfork when we provide a new release, and we will not need to support Masternode owner too much.

**Comment by etienne-napoleone** [comment]
This will probably not be implemented as [tomochain/create-tomochain-masternode](https://github.com/tomochain/create-tomochain-masternode) will be the prefered tool over tmn when it comes out.
