### ISSUE TITLE
Add an option to bind path for chaindata instead of docker named volume

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tmn#47]
Will help when using mounted volumes

**Comment by nyeates** [comment]
Assure it works both at initial tmn start, and keeps said config through subsequent tmn stop, start, upgrade, etc. 

If the option is given *after* first start, the data dir will ideally change.

Tmn inspect might show current data dir, even if the above option is not given. I had wanted to know where my default data dir was, even without wanting the option.

**Comment by etienne-napoleone** [comment]
Thanks for the suggestion @nyeates !
In the meantime, as tmn is a wrapper around docker, you can check where the data is like so:
```bash
# list volumes
docker volume ls

# inspect the masternode volume
docker volume inspect VOLUME_NAME
```

**Comment by etienne-napoleone** [comment]
This will probably not be implemented as [tomochain/create-tomochain-masternode](https://github.com/tomochain/create-tomochain-masternode) will be the prefered tool over tmn when it comes out.
